### PR TITLE
Fix SmsType parsing

### LINKED ISSUE #86: SmsColumn.TYPE | Unhandled Exception: type 'String' is not a subtype of type 'int'
When `getInboxSms()` is invoked with `SmsColumn.TYPE`, an error is throwed

```dart
List<SmsMessage> messages = await Telephony.instance.getInboxSms( columns: [ SmsColumn.TYPE ], );
```

Error:

    [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: type 'String' is not a subtype of type 'int'
    E/flutter (25566): #0 new SmsMessage.fromMap
    package:telephony/telephony.dart:635
    E/flutter (25566): #1 Telephony.getInboxSms. package:telephony/telephony.dart:180
    E/flutter (25566): #2 MappedListIterable.elementAt (dart:_internal/iterable.dart:411:31)
    E/flutter (25566): #3 ListIterator.moveNext (dart:_internal/iterable.dart:340:26)
    E/flutter (25566): #4 new _List._ofEfficientLengthIterable (dart:core-patch/array.dart:93:27)
    E/flutter (25566): #5 new _List.of (dart:core-patch/array.dart:55:20)
    E/flutter (25566): #6 new List.of (dart:core-patch/array_patch.dart:52:20)
    E/flutter (25566): #7 ListIterable.toList (dart:_internal/iterable.dart:211:44)
    E/flutter (25566): #8 Telephony.getInboxSms
    package:telephony/telephony.dart:181

The error is in fromMap() (line 635), becasuse a String is passed to `values[]` enum operator
```dart
case _SmsProjections.TYPE: 
   this.type = SmsType.values[value]; 
   break;
```

Problem also reported by https://github.com/shounakmulay/Telephony/issues/82 which, however, was closed by the author without giving any explanation.

### PR DESCRIPTION
**Pull request by Mabsten**
Fix https://github.com/shounakmulay/Telephony/issues/86
For parsing in `case _SmsProjections.TYPE` I used `int.parse()` and not `int.tryParse()` so that an exception is thrown if parsing fails, which should never happen if there are no bugs 

I'm not familiar with git so please let me know if I did something wrong with the pull request procedure

### CODE REVIEW

File: lib/telephony.dart [hunk 1]
```diff
@@ -632,7 +632,7 @@ class SmsMessage {
           this.threadId = int.tryParse(value);
           break;
         case _SmsProjections.TYPE:
-          this.type = SmsType.values[value];
+          this.type = SmsType.values[int.parse(value)];
```
Comment (shounakmulay) [inline lib/telephony.dart]: I think we should still use `tryParse`. If the value is incorrect it will still throw an error. But just using `parse` will throw an error even if parsing fails for some reason.

**Review by shounakmulay — CHANGES_REQUESTED** [review]

File: lib/telephony.dart (hunk 1 above)
Comment (Mabsten) [reply lib/telephony.dart]: Ok, in fact you used `tryParse()` also for DATE and TIMESTAMP, leaving the SmsMessage field to null if the parsing fails

**Review by shounakmulay — APPROVED** [review]
